"""initial tables

Revision ID: 3350e3c4d86b
Revises: 3a71ec4922aa
Create Date: 2025-10-27 21:10:55.309241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3350e3c4d86b'
down_revision: Union[str, Sequence[str], None] = '3a71ec4922aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debates', 'player2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debates', 'player2_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
